on:
  workflow_dispatch:
  schedule:
  - cron: '45 * * * *'    # <-- Set your cron here (UTC), for syntax see https://crontab.guru/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@master
        with:
            fetch-depth: 1

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Process data 
        run: make all
